name: Build Gravity Mod

on:
  push:
    branches: [main, master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Geode mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          sdk: latest

      - name: Upload Geode mod
        uses: actions/upload-artifact@v4
        with:
          name: Gravity-Mod-Geode
          path: ${{ steps.build.outputs.geode }}